// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usxnzaqxdrphdfccrgew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzeG56YXF4ZHJwaGRmY2NyZ2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzcxMzUsImV4cCI6MjA2MTYxMzEzNX0.f68vbNTLIabVa0t_2Gbvzi5fp643aypHZ4I5TW0Qz1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);