
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://usxnzaqxdrphdfccrgew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzeG56YXF4ZHJwaGRmY2NyZ2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzcxMzUsImV4cCI6MjA2MTYxMzEzNX0.f68vbNTLIabVa0t_2Gbvzi5fp643aypHZ4I5TW0Qz1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
  }
});

// Initialize storage buckets - we're disabling automatic bucket creation
// and assuming the buckets are created in the SQL migration
// or by an admin in the Supabase dashboard
import { ensureStorageBucketsExist } from '@/utils/supabaseStorage';
(async () => {
  try {
    // Make sure the listings bucket exists
    // Comment this out as it requires admin privileges
    // await ensureStorageBucketsExist();
    
    // Check if we can access the storage
    const { data, error } = await supabase.storage.getBucket('listings');
    if (error) {
      console.warn('Listings bucket might not exist:', error);
    } else {
      console.log('Listings bucket accessible:', data);
    }
  } catch (error) {
    console.error('Failed to initialize storage buckets:', error);
  }
})();
